name: Run Bruno CLI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bruno-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno CLI Tests
        run: bru run --env prod --reporter-html ganesh.html


